import { Project, Contractor, Alert, Complaint, Dispute, Guarantee, DuplicateCandidate, AuditLog, OverviewAnalytics } from '../types';

export const INITIAL_CONTRACTORS: Contractor[] = [
  {
    id: "CON-AP-042",
    name: "Sri Venkateswara Infra Projects Ltd",
    registration_no: "AP-PWD-CL1-2018-847",
    category_class: "Class 1 Civil & Infrastructure",
    contact_person: "K. Raghunath Reddy",
    contact_phone: "+91 98480 12345",
    contact_email: "contracts@svinfraltd.in",
    address: "Plot 42, Industrial Estate, Auto Nagar, Visakhapatnam, AP",
    state: "Andhra Pradesh",
    total_contracts: 18,
    total_contract_value: 48200000.0,
    completed_projects: 12,
    delayed_projects: 4,
    disputed_projects: 2,
    terminated_projects: 0,
    average_delay_days: 42.5,
    average_cost_variation_pct: 6.8,
    defect_reports_count: 3,
    active_projects_count: 6,
    performance_score: 68,
    risk_level: "ATTENTION",
    risk_notes: "Multiple concurrent works in Visakhapatnam rural. Moderate milestone delays reported in 2 active community infrastructure works."
  },
  {
    id: "CON-UP-089",
    name: "Purvanchal Nirman Nigam LLP",
    registration_no: "UP-PWD-CL1-2019-112",
    category_class: "Class 1 Public Works",
    contact_person: "Aditya Pratap Singh",
    contact_phone: "+91 94150 98765",
    contact_email: "operations@purvanchalnirman.org",
    address: "Civil Lines, Varanasi, Uttar Pradesh",
    state: "Uttar Pradesh",
    total_contracts: 24,
    total_contract_value: 72500000.0,
    completed_projects: 14,
    delayed_projects: 8,
    disputed_projects: 3,
    terminated_projects: 1,
    average_delay_days: 68.0,
    average_cost_variation_pct: 14.2,
    defect_reports_count: 7,
    active_projects_count: 9,
    performance_score: 45,
    risk_level: "HIGH RISK",
    risk_notes: "Notice issued regarding multiple unresolved defect liability claims in Varanasi & Gorakhpur water projects."
  },
  {
    id: "CON-MH-015",
    name: "Sahyadri Civil Tech Solutions Pvt Ltd",
    registration_no: "MH-PWD-CL1-2020-449",
    category_class: "Class 1 Smart Infrastructure",
    contact_person: "Milind Deshmukh",
    contact_phone: "+91 98220 54321",
    contact_email: "admin@sahyadricivil.co.in",
    address: "Shivajinagar, Pune, Maharashtra",
    state: "Maharashtra",
    total_contracts: 31,
    total_contract_value: 94000000.0,
    completed_projects: 28,
    delayed_projects: 2,
    disputed_projects: 0,
    terminated_projects: 0,
    average_delay_days: 11.2,
    average_cost_variation_pct: 1.4,
    defect_reports_count: 1,
    active_projects_count: 3,
    performance_score: 94,
    risk_level: "LOW RISK",
    risk_notes: "Excellent delivery record. Timely milestone handovers across Pune and Nashik districts."
  },
  {
    id: "CON-KA-078",
    name: "Cauvery Engineering & Builders Corp",
    registration_no: "KA-PWD-CL1-2017-903",
    category_class: "Class 1 Rural Works",
    contact_person: "C. M. Suresh Kumar",
    contact_phone: "+91 94480 33221",
    contact_email: "contact@cauverybuilders.com",
    address: "Yadavagiri Industrial Area, Mysuru, Karnataka",
    state: "Karnataka",
    total_contracts: 15,
    total_contract_value: 36500000.0,
    completed_projects: 9,
    delayed_projects: 4,
    disputed_projects: 2,
    terminated_projects: 0,
    average_delay_days: 54.0,
    average_cost_variation_pct: 8.5,
    defect_reports_count: 4,
    active_projects_count: 6,
    performance_score: 62,
    risk_level: "ATTENTION",
    risk_notes: "Subject to recent cross-scheme duplicate work audit in Mysuru rural road division."
  },
  {
    id: "CON-TN-033",
    name: "Meenakshi Infra Consortium",
    registration_no: "TN-PWD-CL1-2021-301",
    category_class: "Class 1 Healthcare & Institutional",
    contact_person: "S. Sundararaman",
    contact_phone: "+91 94430 77889",
    contact_email: "info@meenakshiinfra.in",
    address: "KK Nagar, Madurai, Tamil Nadu",
    state: "Tamil Nadu",
    total_contracts: 20,
    total_contract_value: 58000000.0,
    completed_projects: 17,
    delayed_projects: 2,
    disputed_projects: 1,
    terminated_projects: 0,
    average_delay_days: 18.0,
    average_cost_variation_pct: 2.8,
    defect_reports_count: 2,
    active_projects_count: 3,
    performance_score: 88,
    risk_level: "LOW RISK",
    risk_notes: "Consistent delivery with verified quality certifications on institutional works."
  },
  {
    id: "CON-BR-061",
    name: "Magadh Nirman Udyog Pvt Ltd",
    registration_no: "BR-PWD-CL2-2019-724",
    category_class: "Class 2 Rural Connectivity",
    contact_person: "Rajeshwar Pandey",
    contact_phone: "+91 99340 44556",
    contact_email: "contact@magadhnirman.in",
    address: "Bailey Road, Patna, Bihar",
    state: "Bihar",
    total_contracts: 14,
    total_contract_value: 29800000.0,
    completed_projects: 6,
    delayed_projects: 6,
    disputed_projects: 2,
    terminated_projects: 0,
    average_delay_days: 78.0,
    average_cost_variation_pct: 11.2,
    defect_reports_count: 5,
    active_projects_count: 8,
    performance_score: 52,
    risk_level: "HIGH RISK",
    risk_notes: "High delay frequency on culvert and village approach road works in Gaya district."
  },
  {
    id: "CON-RJ-022",
    name: "Marwar Water & Energy EPC Ltd",
    registration_no: "RJ-PHED-CL1-2018-518",
    category_class: "Class 1 PHED & Solar",
    contact_person: "Bhanwar Singh Rathore",
    contact_phone: "+91 94140 66778",
    contact_email: "epc@marwarwater.com",
    address: "Industrial Area, Jodhpur, Rajasthan",
    state: "Rajasthan",
    total_contracts: 22,
    total_contract_value: 64000000.0,
    completed_projects: 18,
    delayed_projects: 3,
    disputed_projects: 1,
    terminated_projects: 0,
    average_delay_days: 21.0,
    average_cost_variation_pct: 4.1,
    defect_reports_count: 3,
    active_projects_count: 4,
    performance_score: 82,
    risk_level: "LOW RISK",
    risk_notes: "Specialized in solar pump installations and community RO plants."
  },
  {
    id: "CON-WB-054",
    name: "Bengal Eastern Infra Developers",
    registration_no: "WB-PWD-CL1-2020-612",
    category_class: "Class 1 Public Infrastructure",
    contact_person: "Subhashish Banerjee",
    contact_phone: "+91 98300 88990",
    contact_email: "tenders@bengaleastern.in",
    address: "Salt Lake Sector V, Kolkata, West Bengal",
    state: "West Bengal",
    total_contracts: 19,
    total_contract_value: 51000000.0,
    completed_projects: 13,
    delayed_projects: 5,
    disputed_projects: 1,
    terminated_projects: 0,
    average_delay_days: 46.0,
    average_cost_variation_pct: 7.3,
    defect_reports_count: 4,
    active_projects_count: 6,
    performance_score: 71,
    risk_level: "ATTENTION",
    risk_notes: "Drainage and embankment construction subject to seasonal monsoon extensions."
  },
  {
    id: "CON-DL-009",
    name: "National Urban Tech Infrastructure",
    registration_no: "DL-CPWD-CL1-2016-104",
    category_class: "Class 1 Urban & Electrical",
    contact_person: "Raman Malhotra",
    contact_phone: "+91 98110 22334",
    contact_email: "projects@nationalurbantech.in",
    address: "Connaught Place, New Delhi",
    state: "Delhi",
    total_contracts: 38,
    total_contract_value: 145000000.0,
    completed_projects: 35,
    delayed_projects: 2,
    disputed_projects: 1,
    terminated_projects: 0,
    average_delay_days: 14.0,
    average_cost_variation_pct: 2.1,
    defect_reports_count: 2,
    active_projects_count: 3,
    performance_score: 91,
    risk_level: "LOW RISK",
    risk_notes: "High capacity contractor executing institutional and healthcare electrification works."
  }
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: "MPLAD-AP-2026-00125",
    title: "Construction of Multipurpose Community Hall",
    description: "Construction of an all-weather community hall with solar rooftop and sanitation facilities for rural community events, vocational workshops, and public gatherings.",
    category: "Community Infrastructure",
    status: "UNDER PROGRESS",
    mp_name: "M. Sribharat",
    mp_house: "Lok Sabha",
    state: "Andhra Pradesh",
    district: "Visakhapatnam",
    constituency: "Visakhapatnam",
    mandal_block: "Bheemunipatnam",
    village: "Tagarapuvalasa",
    latitude: 17.9312,
    longitude: 83.4248,
    year: "2025-2026",
    implementing_agency: "Panchayati Raj Engineering Division (PRED)",
    recommended_amount: 3000000.0,
    sanctioned_amount: 2950000.0,
    contract_amount: 2890000.0,
    funds_released: 2500000.0,
    funds_paid: 2140000.0,
    actual_expenditure: 2140000.0,
    physical_progress: 72.0,
    financial_progress: 74.0,
    start_date: "2025-06-15",
    expected_completion_date: "2025-12-10",
    delay_days: 84,
    overall_risk_score: 67,
    risk_level: "HIGH RISK",
    financial_health: 82,
    physical_health: 61,
    contract_health: 74,
    schedule_health: 43,
    evidence_health: 89,
    risk_reasons: [
      "84-day schedule delay beyond sanctioned milestone target",
      "Physical progress (72%) lagging planned target of 92%",
      "Roofing truss procurement delayed due to contractor vendor dispute",
      "Unspent balance of ₹3,60,000 lying in district treasury account"
    ],
    contractor_id: "CON-AP-042",
    contractor_name: "Sri Venkateswara Infra Projects Ltd",
    last_inspected_date: "2026-02-18",
    last_verified_date: "2026-02-20",
    data_source: "MPLADS e-SAKSHI Portal & District Planning Cell",
    source_verification_status: "VERIFIED_GOVERNMENT_RECORD",
    timeline_events: [
      { id: "TL-1", stage_name: "MP Recommendation", stage_order: 1, event_date: "2025-01-15", authority: "Hon'ble MP M. Sribharat", amount: 3000000, document_name: "MP_Proposal_Letter.pdf", verification_status: "VERIFIED" },
      { id: "TL-2", stage_name: "Administrative Sanction", stage_order: 2, event_date: "2025-02-10", authority: "District Collector Visakhapatnam", amount: 2950000, document_name: "Admin_Sanction_Order.pdf", verification_status: "VERIFIED" },
      { id: "TL-3", stage_name: "Technical Sanction", stage_order: 3, event_date: "2025-03-05", authority: "Superintending Engineer PRED", amount: 2950000, document_name: "Technical_Sanction_DPR.pdf", verification_status: "VERIFIED" },
      { id: "TL-4", stage_name: "Tender Notification", stage_order: 4, event_date: "2025-03-25", authority: "Executive Engineer", amount: 2890000, document_name: "NIT_eTender_Notice.pdf", verification_status: "VERIFIED" },
      { id: "TL-5", stage_name: "Contract Award", stage_order: 5, event_date: "2025-04-20", authority: "District Tender Committee", amount: 2890000, document_name: "Contract_Agreement_LOA.pdf", verification_status: "VERIFIED" },
      { id: "TL-6", stage_name: "Fund Release (Tranche 1)", stage_order: 6, event_date: "2025-05-15", authority: "District Planning Office", amount: 1500000, document_name: "Treasury_Disbursement.pdf", verification_status: "VERIFIED" },
      { id: "TL-7", stage_name: "Work Commencement", stage_order: 7, event_date: "2025-06-15", authority: "Executive Engineer & AE", document_name: "Site_Handover_Order.pdf", verification_status: "VERIFIED" },
      { id: "TL-8", stage_name: "Field Inspection #1", stage_order: 8, event_date: "2025-09-12", authority: "Assistant Executive Engineer", document_name: "Inspection_Report_01.pdf", verification_status: "VERIFIED" },
      { id: "TL-9", stage_name: "Progress Measurement", stage_order: 9, event_date: "2025-11-20", authority: "Divisional Accounts Officer", amount: 1000000, document_name: "MB_Measurement_Record.pdf", verification_status: "PARTIAL" },
      { id: "TL-10", stage_name: "Completion & Handover", stage_order: 10, event_date: "Scheduled 2026-04", authority: "Executive Engineer & District Collector", verification_status: "PENDING" }
    ],
    fund_flows: [
      { id: "FF-1", stage: "Funds Available", amount: 3000000, transaction_date: "2025-01-20", reference_no: "TX-GOI-00125-01", source_agency: "MoSPI New Delhi", destination_agency: "District Treasury Visakhapatnam", verification_status: "VERIFIED_GOVERNMENT_RECORD" },
      { id: "FF-2", stage: "Sanctioned", amount: 2950000, transaction_date: "2025-02-15", reference_no: "TX-DPC-00125-02", source_agency: "District Collectorate", destination_agency: "PRED Division Escrow", verification_status: "VERIFIED_GOVERNMENT_RECORD" },
      { id: "FF-3", stage: "Contracted", amount: 2890000, transaction_date: "2025-04-25", reference_no: "TX-AGR-00125-03", source_agency: "PRED Division", destination_agency: "Sri Venkateswara Infra Projects Ltd", verification_status: "VERIFIED_GOVERNMENT_RECORD" },
      { id: "FF-4", stage: "Released", amount: 2500000, transaction_date: "2025-05-18", reference_no: "TX-REL-00125-04", source_agency: "District Nodal Bank", destination_agency: "Project Escrow A/c", verification_status: "VERIFIED_GOVERNMENT_RECORD" },
      { id: "FF-5", stage: "Paid", amount: 2140000, transaction_date: "2025-11-25", reference_no: "TX-PAY-00125-05", source_agency: "Project Escrow A/c", destination_agency: "Sri Venkateswara Infra Projects Ltd", verification_status: "VERIFIED_GOVERNMENT_RECORD" },
      { id: "FF-6", stage: "Expenditure", amount: 2140000, transaction_date: "2026-01-10", reference_no: "TX-EXP-00125-06", source_agency: "Treasury MB", destination_agency: "Site Materials & Masonry Works", verification_status: "VERIFIED_GOVERNMENT_RECORD" }
    ],
    inspections: [
      {
        id: "INSP-AP-01",
        project_id: "MPLAD-AP-2026-00125",
        officer_name: "Shri R. K. Verma, AEE",
        officer_designation: "Assistant Executive Engineer, PRED",
        inspection_date: "2026-02-18",
        latitude: 17.9313,
        longitude: 83.4249,
        gps_matched: true,
        distance_variance_meters: 14.5,
        physical_progress_observed: 72.0,
        quality_rating: "Satisfactory",
        material_observations: "Cement grade 43 PPC, tested aggregate on site. Structural columns and lintels cast.",
        labour_activity_observations: "18 workers on site. Roof truss fabrication pending vendor dispatch.",
        general_remarks: "Work verified against milestone DPR. Notice issued for roofing acceleration.",
        defects_reported: "Minor honeycombing on column #4 patched and cured.",
        stalled_status: false,
        photo_urls: [
          "https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600",
          "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600"
        ],
        ai_cv_similarity_score: 0.88,
        ai_progress_discrepancy_pct: 2.0,
        ai_verification_notes: "Geotag confirmed within 15 meters of sanctioned point. Timestamp hash valid.",
        status: "VERIFIED"
      }
    ],
    complaints: [
      {
        id: "CMP-2026-00482",
        project_id: "MPLAD-AP-2026-00125",
        citizen_name: "Tagarapuvalasa Gram Panchayat Residents",
        citizen_phone: "+91 98481 XXXXX",
        citizen_email: "panchayat.visakha@gmail.com",
        category: "Work stopped",
        description: "Roofing work paused for past 3 weeks. Hall needed before monsoon wedding and harvest festival season.",
        evidence_photo_url: "https://images.unsplash.com/photo-1590381105924-c72589b9ef3f?w=600",
        location: "Tagarapuvalasa Main Road",
        submission_date: "2026-01-28",
        status: "INVESTIGATION",
        assigned_to: "Assistant Executive Engineer PRED",
        resolution_notes: "Contractor directed to resume truss erection by Feb 25."
      }
    ],
    disputes: [
      {
        id: "DSP-2026-00125",
        project_id: "MPLAD-AP-2026-00125",
        dispute_type: "Progress dispute",
        claimant: "Contractor",
        contractor_claim_progress: 80.0,
        officer_inspected_progress: 72.0,
        financial_progress_record: 74.0,
        ai_evidence_consistency: "Medium",
        claimed_amount: 350000.0,
        description: "Contractor submitted running account bill claiming 80% completion citing fabricated steel purchased off-site.",
        status: "UNDER_INVESTIGATION",
        resolution_summary: "Joint measurement scheduled for physical verification of structural steel."
      }
    ],
    guarantees: [
      {
        id: "PBG-AP-00125",
        project_id: "MPLAD-AP-2026-00125",
        contractor_name: "Sri Venkateswara Infra Projects Ltd",
        guarantee_type: "Performance Bank Guarantee",
        bank_or_institution: "State Bank of India, Auto Nagar Branch",
        amount: 144500.0,
        issue_date: "2025-04-22",
        expiry_date: "2026-04-30",
        days_to_expiry: 56,
        status: "ACTIVE",
        action_required: false,
        defects_logged: "Routine inspection required before final defect liability period.",
        contractor_response: "Guarantees valid up to scheduled handover date."
      }
    ],
    alerts: [
      {
        id: "ALT-2026-00125",
        project_id: "MPLAD-AP-2026-00125",
        project_title: "Construction of Multipurpose Community Hall",
        severity: "HIGH",
        category: "Schedule Delay",
        title: "Potential Anomaly: 84-day Schedule Delay in MPLAD-AP-2026-00125",
        description: "Surveillance flagged 84-day schedule delay beyond sanctioned milestone target. Contractor claimed 80% progress vs verified 72% on site.",
        observed_data: "Reported Physical Progress: 72%, Financial Disbursal: 74%, Elapsed Time: 110%",
        expected_data: "Scheduled Physical Progress: 92%",
        difference: "20 percentage points physical lag; 84 days schedule deviation",
        confidence_score: 0.91,
        recommended_action: "Execute joint physical verification and issue milestone catch-up directive to contractor.",
        escalation_level: "Level 3 - District Authority",
        assigned_authority: "District Planning Officer, Visakhapatnam",
        due_days: 7,
        status: "OPEN",
        created_at: "2026-02-18",
        audit_history: [
          { time: "2026-02-18 09:30", action: "Anomaly Flagged by Surveillance Engine", actor: "AI Engine" },
          { time: "2026-02-18 10:15", action: "Assigned to District Planning Officer", actor: "System Routing" }
        ]
      }
    ]
  },
  {
    id: "MPLAD-UP-2026-00084",
    title: "Solar-Powered Drinking Water RO Purification Plant",
    description: "Installation of 1000 LPH solar dual-powered RO water purification plant with 5000-liter elevated storage reservoir and 4 public dispensing kiosks.",
    category: "Drinking Water",
    status: "UNDER PROGRESS",
    mp_name: "Narendra Modi",
    mp_house: "Lok Sabha",
    state: "Uttar Pradesh",
    district: "Varanasi",
    constituency: "Varanasi",
    mandal_block: "Sevapuri",
    village: "Khadan",
    latitude: 25.3216,
    longitude: 82.8124,
    year: "2025-2026",
    implementing_agency: "UP Jal Nigam (Rural)",
    recommended_amount: 2500000.0,
    sanctioned_amount: 2400000.0,
    contract_amount: 2350000.0,
    funds_released: 2350000.0,
    funds_paid: 2200000.0,
    actual_expenditure: 2200000.0,
    physical_progress: 55.0,
    financial_progress: 91.5,
    start_date: "2025-05-10",
    expected_completion_date: "2025-11-15",
    delay_days: 110,
    overall_risk_score: 89,
    risk_level: "CRITICAL",
    financial_health: 48,
    physical_health: 35,
    contract_health: 52,
    schedule_health: 30,
    evidence_health: 60,
    risk_reasons: [
      "110-day severe schedule slippage",
      "Acute financial vs physical disparity: 91.5% funds disbursed vs 55% physical execution (Δ 36.5%)",
      "Contractor submitted claim for membrane delivery not verified on site by Jal Nigam AE",
      "Performance Bank Guarantee expires in 18 days — mandatory extension required"
    ],
    contractor_id: "CON-UP-089",
    contractor_name: "Purvanchal Nirman Nigam LLP",
    last_inspected_date: "2026-02-12",
    last_verified_date: "2026-02-14",
    data_source: "Jal Nigam e-Tendering & e-SAKSHI State Data Node",
    source_verification_status: "VERIFIED_GOVERNMENT_RECORD",
    guarantees: [
      {
        id: "PBG-UP-00084",
        project_id: "MPLAD-UP-2026-00084",
        contractor_name: "Purvanchal Nirman Nigam LLP",
        guarantee_type: "Performance Bank Guarantee",
        bank_or_institution: "Punjab National Bank, Varanasi Main",
        amount: 117500.0,
        issue_date: "2025-04-10",
        expiry_date: "2026-03-22",
        days_to_expiry: 18,
        status: "EXPIRING_SOON",
        action_required: true,
        defects_logged: "Mandatory PBG extension notice issued to contractor. Risk of guarantee lapse during incomplete work.",
        contractor_response: "Awaiting bank revalidation certificate."
      }
    ],
    alerts: [
      {
        id: "ALT-2026-00084",
        project_id: "MPLAD-UP-2026-00084",
        project_title: "Solar-Powered Drinking Water RO Purification Plant",
        severity: "CRITICAL",
        category: "Fund Mismatch",
        title: "CRITICAL: Severe Progress Disparity & Expiring Guarantee (18 days)",
        description: "Financial progress at 91.5% while physical progress certified at only 55%. PBG expiring in 18 days.",
        observed_data: "Financial Progress: 91.5% | Physical Progress: 55% | PBG Expiry: 18 days",
        expected_data: "Financial vs Physical correlation within 10%",
        difference: "36.5 percentage points disbursement surplus without completed commissioning",
        confidence_score: 0.94,
        recommended_action: "Freeze next tranche disbursal. Issue immediate PBG extension order or invoke guarantee.",
        escalation_level: "Level 3 - District Authority",
        assigned_authority: "Chief Development Officer / District Magistrate Varanasi",
        due_days: 3,
        status: "OPEN",
        created_at: "2026-02-14",
        audit_history: [
          { time: "2026-02-14 11:20", action: "Critical Disparity Flagged", actor: "AI Engine" }
        ]
      }
    ]
  },
  {
    id: "MPLAD-MH-2026-00214",
    title: "Smart Digital Classrooms & Science Lab in Zilla Parishad High School",
    description: "Establishment of interactive flat panel smart classrooms, STEM lab kits, high-speed networking, and 5kVA solar backup for 600 rural students.",
    category: "Education",
    status: "COMPLETED",
    mp_name: "Murlidhar Mohol",
    mp_house: "Lok Sabha",
    state: "Maharashtra",
    district: "Pune",
    constituency: "Pune",
    mandal_block: "Haveli",
    village: "Wagholi",
    latitude: 18.5793,
    longitude: 73.9809,
    year: "2025-2026",
    implementing_agency: "Zilla Parishad Education Works Division",
    recommended_amount: 1800000.0,
    sanctioned_amount: 1750000.0,
    contract_amount: 1720000.0,
    funds_released: 1720000.0,
    funds_paid: 1720000.0,
    actual_expenditure: 1720000.0,
    physical_progress: 100.0,
    financial_progress: 100.0,
    start_date: "2025-07-01",
    expected_completion_date: "2025-11-30",
    delay_days: 0,
    overall_risk_score: 12,
    risk_level: "NORMAL",
    financial_health: 98,
    physical_health: 99,
    contract_health: 96,
    schedule_health: 98,
    evidence_health: 97,
    risk_reasons: [
      "Project successfully completed within sanction amount and timeline",
      "Complete photographic and geo-tagged evidence verified",
      "Joint inspection certificate signed by BDO and Headmaster"
    ],
    contractor_id: "CON-MH-015",
    contractor_name: "Sahyadri Civil Tech Solutions Pvt Ltd",
    last_inspected_date: "2025-12-05",
    last_verified_date: "2025-12-08",
    data_source: "Maharashtra e-Panchayat & PWD Portal",
    source_verification_status: "VERIFIED_GOVERNMENT_RECORD"
  },
  {
    id: "MPLAD-KA-2026-00302",
    title: "Cement Concrete (CC) Road from Main Temple to SC/ST Colony",
    description: "Laying of M-30 grade CC road with side stormwater drains and culvert over 1.2 km stretch connecting village temple to habitation colony.",
    category: "Roads & Bridges",
    status: "UNDER PROGRESS",
    mp_name: "Yaduveer Krishnadatta Chamaraja Wadiyar",
    mp_house: "Lok Sabha",
    state: "Karnataka",
    district: "Mysuru",
    constituency: "Mysore",
    mandal_block: "Hunsur",
    village: "Biligere",
    latitude: 12.3082,
    longitude: 76.2891,
    year: "2025-2026",
    implementing_agency: "Karnataka Rural Infrastructure Development Ltd (KRIDL)",
    recommended_amount: 3500000.0,
    sanctioned_amount: 3400000.0,
    contract_amount: 3320000.0,
    funds_released: 2800000.0,
    funds_paid: 2200000.0,
    actual_expenditure: 2200000.0,
    physical_progress: 62.0,
    financial_progress: 64.7,
    start_date: "2025-08-01",
    expected_completion_date: "2026-01-15",
    delay_days: 49,
    overall_risk_score: 78,
    risk_level: "CRITICAL",
    financial_health: 70,
    physical_health: 55,
    contract_health: 60,
    schedule_health: 52,
    evidence_health: 40,
    risk_reasons: [
      "AI Alert: Potential Duplicate Work flagged with 93% similarity to Zilla Panchayat Grant Work #ZP-MYS-2025-088 on same stretch",
      "Geotagged start coordinate aligns within 45m of previously sanctioned PWD road",
      "49-day execution delay; drain excavation incomplete at culvert crossing"
    ],
    contractor_id: "CON-KA-078",
    contractor_name: "Cauvery Engineering & Builders Corp",
    last_inspected_date: "2026-02-10",
    last_verified_date: "2026-02-15",
    data_source: "KRIDL Karnataka & e-Manaswini System",
    source_verification_status: "VERIFIED_GOVERNMENT_RECORD"
  }
];

export const INITIAL_DUPLICATES: DuplicateCandidate[] = [
  {
    id: "DUP-KA-00302-00199",
    project_a_id: "MPLAD-KA-2026-00302",
    project_a_title: "Cement Concrete (CC) Road from Main Temple to SC/ST Colony",
    project_b_id: "MPLAD-KA-2025-00199",
    project_b_title: "Formation and Concreting of Habitation Road in Biligere",
    similarity_score: 93,
    matched_factors: [
      "Identical Category: Roads & Bridges",
      "Same Village: Biligere",
      "GPS Proximity: ~45 meters apart",
      "Title Overlap (82% keyword match)",
      "Comparable Sanction Value (₹34,00,000 vs ₹31,00,000)"
    ],
    district: "Mysuru",
    status: "PENDING_REVIEW"
  },
  {
    id: "DUP-UP-00084-00102",
    project_a_id: "MPLAD-UP-2026-00084",
    project_a_title: "Solar-Powered Drinking Water RO Purification Plant",
    project_b_id: "MPLAD-UP-2025-00102",
    project_b_title: "Installation of Community RO Drinking Water System in Khadan",
    similarity_score: 87,
    matched_factors: [
      "Identical Category: Drinking Water",
      "Same Village: Khadan, Sevapuri",
      "GPS Proximity: ~110 meters apart",
      "Overlapping Beneficiary Habitation"
    ],
    district: "Varanasi",
    status: "PENDING_REVIEW"
  }
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: "LOG-0815-00125",
    timestamp: "2026-02-28 08:15:00",
    actor_role: "District Authority",
    actor_name: "District Collector Visakhapatnam",
    action: "PROJECT_VIEWED",
    entity_id: "MPLAD-AP-2026-00125",
    details: "Opened 360 trace dossier for review",
    ip_address: "10.42.18.5"
  },
  {
    id: "LOG-0830-00084",
    timestamp: "2026-02-28 08:30:00",
    actor_role: "System AI",
    actor_name: "Surveillance Engine",
    action: "AI_ANOMALY_GENERATED",
    entity_id: "MPLAD-UP-2026-00084",
    details: "Flagged 110-day delay and 36.5% physical vs financial disparity",
    ip_address: "127.0.0.1"
  },
  {
    id: "LOG-0845-00125",
    timestamp: "2026-02-28 08:45:00",
    actor_role: "Field Officer",
    actor_name: "Shri R. K. Verma, AEE",
    action: "INSPECTION_SUBMITTED",
    entity_id: "MPLAD-AP-2026-00125",
    details: "Submitted milestone #2 physical verification report with geotagged images",
    ip_address: "10.42.18.89"
  },
  {
    id: "LOG-0912-00084",
    timestamp: "2026-02-28 09:12:00",
    actor_role: "District Authority",
    actor_name: "Chief Planning Officer",
    action: "ALERT_ESCALATED",
    entity_id: "ALT-2026-00084",
    details: "Escalated to Superintending Engineer Jal Nigam with 7-day compliance SLA",
    ip_address: "10.42.18.5"
  }
];
