"""
MPLAD-TRACE 360 Comprehensive Seed Dataset
Contains realistic Indian public works, contractors, contracts, fund flows,
inspections, disputes, guarantees, alerts, and audit logs.
"""

from typing import List, Dict, Any

CONTRACTORS_DATA: List[Dict[str, Any]] = [
    {
        "id": "CON-AP-042",
        "name": "Sri Venkateswara Infra Projects Ltd",
        "registration_no": "AP-PWD-CL1-2018-847",
        "category_class": "Class 1 Civil & Infrastructure",
        "contact_person": "K. Raghunath Reddy",
        "contact_phone": "+91 98480 12345",
        "contact_email": "contracts@svinfraltd.in",
        "address": "Plot 42, Industrial Estate, Auto Nagar, Visakhapatnam, AP",
        "state": "Andhra Pradesh",
        "total_contracts": 18,
        "total_contract_value": 48200000.0,
        "completed_projects": 12,
        "delayed_projects": 4,
        "disputed_projects": 2,
        "terminated_projects": 0,
        "average_delay_days": 42.5,
        "average_cost_variation_pct": 6.8,
        "defect_reports_count": 3,
        "active_projects_count": 6,
        "performance_score": 68,
        "risk_level": "ATTENTION",
        "risk_notes": "Multiple concurrent works in Visakhapatnam rural. Moderate milestone delays reported in 2 active community infrastructure works."
    },
    {
        "id": "CON-UP-089",
        "name": "Purvanchal Nirman Nigam LLP",
        "registration_no": "UP-PWD-CL1-2019-112",
        "category_class": "Class 1 Public Works",
        "contact_person": "Aditya Pratap Singh",
        "contact_phone": "+91 94150 98765",
        "contact_email": "operations@purvanchalnirman.org",
        "address": "Civil Lines, Varanasi, Uttar Pradesh",
        "state": "Uttar Pradesh",
        "total_contracts": 24,
        "total_contract_value": 72500000.0,
        "completed_projects": 14,
        "delayed_projects": 8,
        "disputed_projects": 3,
        "terminated_projects": 1,
        "average_delay_days": 68.0,
        "average_cost_variation_pct": 14.2,
        "defect_reports_count": 7,
        "active_projects_count": 9,
        "performance_score": 45,
        "risk_level": "HIGH RISK",
        "risk_notes": "Notice issued regarding multiple unresolved defect liability claims in Varanasi & Gorakhpur water projects."
    },
    {
        "id": "CON-MH-015",
        "name": "Sahyadri Civil Tech Solutions Pvt Ltd",
        "registration_no": "MH-PWD-CL1-2020-449",
        "category_class": "Class 1 Smart Infrastructure",
        "contact_person": "Milind Deshmukh",
        "contact_phone": "+91 98220 54321",
        "contact_email": "admin@sahyadricivil.co.in",
        "address": "Shivajinagar, Pune, Maharashtra",
        "state": "Maharashtra",
        "total_contracts": 31,
        "total_contract_value": 94000000.0,
        "completed_projects": 28,
        "delayed_projects": 2,
        "disputed_projects": 0,
        "terminated_projects": 0,
        "average_delay_days": 11.2,
        "average_cost_variation_pct": 1.4,
        "defect_reports_count": 1,
        "active_projects_count": 3,
        "performance_score": 94,
        "risk_level": "LOW RISK",
        "risk_notes": "Excellent delivery record. Timely milestone handovers across Pune and Nashik districts."
    },
    {
        "id": "CON-KA-078",
        "name": "Cauvery Engineering & Builders Corp",
        "registration_no": "KA-PWD-CL1-2017-903",
        "category_class": "Class 1 Rural Works",
        "contact_person": "C. M. Suresh Kumar",
        "contact_phone": "+91 94480 33221",
        "contact_email": "contact@cauverybuilders.com",
        "address": "Yadavagiri Industrial Area, Mysuru, Karnataka",
        "state": "Karnataka",
        "total_contracts": 15,
        "total_contract_value": 36500000.0,
        "completed_projects": 9,
        "delayed_projects": 4,
        "disputed_projects": 2,
        "terminated_projects": 0,
        "average_delay_days": 54.0,
        "average_cost_variation_pct": 8.5,
        "defect_reports_count": 4,
        "active_projects_count": 6,
        "performance_score": 62,
        "risk_level": "ATTENTION",
        "risk_notes": "Subject to recent cross-scheme duplicate work audit in Mysuru rural road division."
    },
    {
        "id": "CON-TN-033",
        "name": "Meenakshi Infra Consortium",
        "registration_no": "TN-PWD-CL1-2021-301",
        "category_class": "Class 1 Healthcare & Institutional",
        "contact_person": "S. Sundararaman",
        "contact_phone": "+91 94430 77889",
        "contact_email": "info@meenakshiinfra.in",
        "address": "KK Nagar, Madurai, Tamil Nadu",
        "state": "Tamil Nadu",
        "total_contracts": 20,
        "total_contract_value": 58000000.0,
        "completed_projects": 17,
        "delayed_projects": 2,
        "disputed_projects": 1,
        "terminated_projects": 0,
        "average_delay_days": 18.0,
        "average_cost_variation_pct": 2.8,
        "defect_reports_count": 2,
        "active_projects_count": 3,
        "performance_score": 88,
        "risk_level": "LOW RISK",
        "risk_notes": "Consistent delivery with verified quality certifications on institutional works."
    },
    {
        "id": "CON-BR-061",
        "name": "Magadh Nirman Udyog Pvt Ltd",
        "registration_no": "BR-PWD-CL2-2019-724",
        "category_class": "Class 2 Rural Connectivity",
        "contact_person": "Rajeshwar Pandey",
        "contact_phone": "+91 99340 44556",
        "contact_email": "contact@magadhnirman.in",
        "address": "Bailey Road, Patna, Bihar",
        "state": "Bihar",
        "total_contracts": 14,
        "total_contract_value": 29800000.0,
        "completed_projects": 6,
        "delayed_projects": 6,
        "disputed_projects": 2,
        "terminated_projects": 0,
        "average_delay_days": 78.0,
        "average_cost_variation_pct": 11.2,
        "defect_reports_count": 5,
        "active_projects_count": 8,
        "performance_score": 52,
        "risk_level": "HIGH RISK",
        "risk_notes": "High delay frequency on culvert and village approach road works in Gaya district."
    },
    {
        "id": "CON-RJ-022",
        "name": "Marwar Water & Energy EPC Ltd",
        "registration_no": "RJ-PHED-CL1-2018-518",
        "category_class": "Class 1 PHED & Solar",
        "contact_person": "Bhanwar Singh Rathore",
        "contact_phone": "+91 94140 66778",
        "contact_email": "epc@marwarwater.com",
        "address": "Industrial Area, Jodhpur, Rajasthan",
        "state": "Rajasthan",
        "total_contracts": 22,
        "total_contract_value": 64000000.0,
        "completed_projects": 18,
        "delayed_projects": 3,
        "disputed_projects": 1,
        "terminated_projects": 0,
        "average_delay_days": 21.0,
        "average_cost_variation_pct": 4.1,
        "defect_reports_count": 3,
        "active_projects_count": 4,
        "performance_score": 82,
        "risk_level": "LOW RISK",
        "risk_notes": "Specialized in solar pump installations and community RO plants."
    },
    {
        "id": "CON-WB-054",
        "name": "Bengal Eastern Infra Developers",
        "registration_no": "WB-PWD-CL1-2020-612",
        "category_class": "Class 1 Public Infrastructure",
        "contact_person": "Subhashish Banerjee",
        "contact_phone": "+91 98300 88990",
        "contact_email": "tenders@bengaleastern.in",
        "address": "Salt Lake Sector V, Kolkata, West Bengal",
        "state": "West Bengal",
        "total_contracts": 19,
        "total_contract_value": 51000000.0,
        "completed_projects": 13,
        "delayed_projects": 5,
        "disputed_projects": 1,
        "terminated_projects": 0,
        "average_delay_days": 46.0,
        "average_cost_variation_pct": 7.3,
        "defect_reports_count": 4,
        "active_projects_count": 6,
        "performance_score": 71,
        "risk_level": "ATTENTION",
        "risk_notes": "Drainage and embankment construction subject to seasonal monsoon extensions."
    },
    {
        "id": "CON-DL-009",
        "name": "National Urban Tech Infrastructure",
        "registration_no": "DL-CPWD-CL1-2016-104",
        "category_class": "Class 1 Urban & Electrical",
        "contact_person": "Raman Malhotra",
        "contact_phone": "+91 98110 22334",
        "contact_email": "projects@nationalurbantech.in",
        "address": "Connaught Place, New Delhi",
        "state": "Delhi",
        "total_contracts": 38,
        "total_contract_value": 145000000.0,
        "completed_projects": 35,
        "delayed_projects": 2,
        "disputed_projects": 1,
        "terminated_projects": 0,
        "average_delay_days": 14.0,
        "average_cost_variation_pct": 2.1,
        "defect_reports_count": 2,
        "active_projects_count": 3,
        "performance_score": 91,
        "risk_level": "LOW RISK",
        "risk_notes": "High capacity contractor executing institutional and healthcare electrification works."
    },
    {
        "id": "CON-GJ-047",
        "name": "Sardar Patel Rural Builders LLP",
        "registration_no": "GJ-R&B-CL1-2019-338",
        "category_class": "Class 1 Roads & Bridges",
        "contact_person": "Ketankumar Patel",
        "contact_phone": "+91 98250 11223",
        "contact_email": "contact@spbuilders.in",
        "address": "GIDC Estate, Vadodara, Gujarat",
        "state": "Gujarat",
        "total_contracts": 25,
        "total_contract_value": 78000000.0,
        "completed_projects": 22,
        "delayed_projects": 2,
        "disputed_projects": 0,
        "terminated_projects": 0,
        "average_delay_days": 9.5,
        "average_cost_variation_pct": 1.2,
        "defect_reports_count": 1,
        "active_projects_count": 3,
        "performance_score": 96,
        "risk_level": "LOW RISK",
        "risk_notes": "Consistently early completion rate with high quality audit scores."
    },
    {
        "id": "CON-KL-029",
        "name": "Malabar Eco Constructions",
        "registration_no": "KL-PWD-CL2-2020-819",
        "category_class": "Class 2 Eco & Masonry",
        "contact_person": "P. K. Narayanan",
        "contact_phone": "+91 94470 55667",
        "contact_email": "malabareco@gmail.com",
        "address": "Civil Station Road, Kozhikode, Kerala",
        "state": "Kerala",
        "total_contracts": 12,
        "total_contract_value": 24000000.0,
        "completed_projects": 10,
        "delayed_projects": 1,
        "disputed_projects": 0,
        "terminated_projects": 0,
        "average_delay_days": 15.0,
        "average_cost_variation_pct": 3.0,
        "defect_reports_count": 0,
        "active_projects_count": 2,
        "performance_score": 89,
        "risk_level": "LOW RISK",
        "risk_notes": "Specializes in rainwater harvesting and eco-friendly community structures."
    },
    {
        "id": "CON-OR-038",
        "name": "Kalinga Coastal Projects Ltd",
        "registration_no": "OR-RD-CL1-2018-672",
        "category_class": "Class 1 Rural Development",
        "contact_person": "Debabrata Mohanty",
        "contact_phone": "+91 94370 99887",
        "contact_email": "kalingacoastal@rediffmail.com",
        "address": "Saheed Nagar, Bhubaneswar, Odisha",
        "state": "Odisha",
        "total_contracts": 17,
        "total_contract_value": 41500000.0,
        "completed_projects": 11,
        "delayed_projects": 5,
        "disputed_projects": 1,
        "terminated_projects": 0,
        "average_delay_days": 52.0,
        "average_cost_variation_pct": 8.0,
        "defect_reports_count": 3,
        "active_projects_count": 6,
        "performance_score": 67,
        "risk_level": "ATTENTION",
        "risk_notes": "Frequent delay notices linked to supply chain bottlenecks in coastal blocks."
    },
    {
        "id": "CON-MP-082",
        "name": "Narmada Valley Engineers & Contractors",
        "registration_no": "MP-PWD-CL1-2017-491",
        "category_class": "Class 1 Civil & Water",
        "contact_person": "Virendra Chouhan",
        "contact_phone": "+91 94250 33445",
        "contact_email": "info@narmadavalleyeng.com",
        "address": "Arera Colony, Bhopal, Madhya Pradesh",
        "state": "Madhya Pradesh",
        "total_contracts": 21,
        "total_contract_value": 56000000.0,
        "completed_projects": 15,
        "delayed_projects": 4,
        "disputed_projects": 2,
        "terminated_projects": 0,
        "average_delay_days": 44.0,
        "average_cost_variation_pct": 6.5,
        "defect_reports_count": 3,
        "active_projects_count": 6,
        "performance_score": 73,
        "risk_level": "ATTENTION",
        "risk_notes": "Rural check dam and pond renovation projects under routine district monitoring."
    },
    {
        "id": "CON-PB-019",
        "name": "Punjab Agro-Infra Tech Pvt Ltd",
        "registration_no": "PB-PWD-CL1-2019-082",
        "category_class": "Class 1 Agro & Rural Roads",
        "contact_person": "Harpreet Singh Sandhu",
        "contact_phone": "+91 98140 77665",
        "contact_email": "contact@punjabagroinfra.com",
        "address": "GT Road, Ludhiana, Punjab",
        "state": "Punjab",
        "total_contracts": 16,
        "total_contract_value": 45000000.0,
        "completed_projects": 14,
        "delayed_projects": 1,
        "disputed_projects": 0,
        "terminated_projects": 0,
        "average_delay_days": 12.0,
        "average_cost_variation_pct": 2.0,
        "defect_reports_count": 1,
        "active_projects_count": 2,
        "performance_score": 92,
        "risk_level": "LOW RISK",
        "risk_notes": "Well-equipped road paver fleet with strong adherence to quality specifications."
    },
    {
        "id": "CON-JH-066",
        "name": "Chotanagpur Mining & Civil Works",
        "registration_no": "JH-RCD-CL2-2020-551",
        "category_class": "Class 2 Tribal Area Infrastructure",
        "contact_person": "Binod Soren",
        "contact_phone": "+91 99310 12389",
        "contact_email": "chotanagpurcivil@yahoo.co.in",
        "address": "Main Road, Ranchi, Jharkhand",
        "state": "Jharkhand",
        "total_contracts": 13,
        "total_contract_value": 27500000.0,
        "completed_projects": 7,
        "delayed_projects": 5,
        "disputed_projects": 2,
        "terminated_projects": 0,
        "average_delay_days": 62.0,
        "average_cost_variation_pct": 9.5,
        "defect_reports_count": 4,
        "active_projects_count": 6,
        "performance_score": 58,
        "risk_level": "ATTENTION",
        "risk_notes": "Remote tribal area connectivity projects affected by terrain and seasonal logistics."
    }
]

# Primary Flagship & Core Projects Data
PROJECTS_RAW = [
    {
        "id": "MPLAD-AP-2026-00125",
        "title": "Construction of Multipurpose Community Hall",
        "description": "Construction of an all-weather community hall with solar rooftop and sanitation facilities for rural community events, vocational workshops, and public gatherings.",
        "category": "Community Infrastructure",
        "status": "UNDER PROGRESS",
        "mp_name": "M. Sribharat",
        "mp_house": "Lok Sabha",
        "state": "Andhra Pradesh",
        "district": "Visakhapatnam",
        "constituency": "Visakhapatnam",
        "mandal_block": "Bheemunipatnam",
        "village": "Tagarapuvalasa",
        "latitude": 17.9312,
        "longitude": 83.4248,
        "year": "2025-2026",
        "implementing_agency": "Panchayati Raj Engineering Division (PRED)",
        "recommended_amount": 3000000.0,
        "sanctioned_amount": 2950000.0,
        "contract_amount": 2890000.0,
        "funds_released": 2500000.0,
        "funds_paid": 2140000.0,
        "actual_expenditure": 2140000.0,
        "physical_progress": 72.0,
        "financial_progress": 74.0,
        "start_date": "2025-06-15",
        "expected_completion_date": "2025-12-10",
        "delay_days": 84,
        "overall_risk_score": 67,
        "risk_level": "HIGH RISK",
        "financial_health": 82,
        "physical_health": 61,
        "contract_health": 74,
        "schedule_health": 43,
        "evidence_health": 89,
        "risk_reasons": [
            "84-day schedule delay beyond sanctioned milestone target",
            "Physical progress (72%) lagging planned target of 92%",
            "Roofing truss procurement delayed due to contractor vendor dispute",
            "Unspent balance of ₹3,60,000 lying in district treasury account"
        ],
        "contractor_id": "CON-AP-042",
        "contractor_name": "Sri Venkateswara Infra Projects Ltd",
        "last_inspected_date": "2026-02-18",
        "last_verified_date": "2026-02-20",
        "data_source": "MPLADS e-SAKSHI Portal & District Planning Cell",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-UP-2026-00084",
        "title": "Solar-Powered Drinking Water RO Purification Plant",
        "description": "Installation of 1000 LPH solar dual-powered RO water purification plant with 5000-liter elevated storage reservoir and 4 public dispensing kiosks.",
        "category": "Drinking Water",
        "status": "UNDER PROGRESS",
        "mp_name": "Narendra Modi",
        "mp_house": "Lok Sabha",
        "state": "Uttar Pradesh",
        "district": "Varanasi",
        "constituency": "Varanasi",
        "mandal_block": "Sevapuri",
        "village": "Khadan",
        "latitude": 25.3216,
        "longitude": 82.8124,
        "year": "2025-2026",
        "implementing_agency": "UP Jal Nigam (Rural)",
        "recommended_amount": 2500000.0,
        "sanctioned_amount": 2400000.0,
        "contract_amount": 2350000.0,
        "funds_released": 2350000.0,
        "funds_paid": 2200000.0,
        "actual_expenditure": 2200000.0,
        "physical_progress": 55.0,
        "financial_progress": 91.5,
        "start_date": "2025-05-10",
        "expected_completion_date": "2025-11-15",
        "delay_days": 110,
        "overall_risk_score": 89,
        "risk_level": "CRITICAL",
        "financial_health": 48,
        "physical_health": 35,
        "contract_health": 52,
        "schedule_health": 30,
        "evidence_health": 60,
        "risk_reasons": [
            "110-day severe schedule slippage",
            "Acute financial vs physical disparity: 91.5% funds disbursed vs 55% physical execution (Δ 36.5%)",
            "Contractor submitted claim for membrane delivery not verified on site by Jal Nigam AE",
            "Performance Bank Guarantee expires in 18 days — mandatory extension required"
        ],
        "contractor_id": "CON-UP-089",
        "contractor_name": "Purvanchal Nirman Nigam LLP",
        "last_inspected_date": "2026-02-12",
        "last_verified_date": "2026-02-14",
        "data_source": "Jal Nigam e-Tendering & e-SAKSHI State Data Node",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-MH-2026-00214",
        "title": "Smart Digital Classrooms & Science Lab in Zilla Parishad High School",
        "description": "Establishment of interactive flat panel smart classrooms, STEM lab kits, high-speed networking, and 5kVA solar backup for 600 rural students.",
        "category": "Education",
        "status": "COMPLETED",
        "mp_name": "Murlidhar Mohol",
        "mp_house": "Lok Sabha",
        "state": "Maharashtra",
        "district": "Pune",
        "constituency": "Pune",
        "mandal_block": "Haveli",
        "village": "Wagholi",
        "latitude": 18.5793,
        "longitude": 73.9809,
        "year": "2025-2026",
        "implementing_agency": "Zilla Parishad Education Works Division",
        "recommended_amount": 1800000.0,
        "sanctioned_amount": 1750000.0,
        "contract_amount": 1720000.0,
        "funds_released": 1720000.0,
        "funds_paid": 1720000.0,
        "actual_expenditure": 1720000.0,
        "physical_progress": 100.0,
        "financial_progress": 100.0,
        "start_date": "2025-07-01",
        "expected_completion_date": "2025-11-30",
        "delay_days": 0,
        "overall_risk_score": 12,
        "risk_level": "NORMAL",
        "financial_health": 98,
        "physical_health": 99,
        "contract_health": 96,
        "schedule_health": 98,
        "evidence_health": 97,
        "risk_reasons": [
            "Project successfully completed within sanction amount and timeline",
            "Complete photographic and geo-tagged evidence verified",
            "Joint inspection certificate signed by BDO and Headmaster"
        ],
        "contractor_id": "CON-MH-015",
        "contractor_name": "Sahyadri Civil Tech Solutions Pvt Ltd",
        "last_inspected_date": "2025-12-05",
        "last_verified_date": "2025-12-08",
        "data_source": "Maharashtra e-Panchayat & PWD Portal",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-KA-2026-00302",
        "title": "Cement Concrete (CC) Road from Main Temple to SC/ST Colony",
        "description": "Laying of M-30 grade CC road with side stormwater drains and culvert over 1.2 km stretch connecting village temple to habitation colony.",
        "category": "Roads & Bridges",
        "status": "UNDER PROGRESS",
        "mp_name": "Yaduveer Krishnadatta Chamaraja Wadiyar",
        "mp_house": "Lok Sabha",
        "state": "Karnataka",
        "district": "Mysuru",
        "constituency": "Mysore",
        "mandal_block": "Hunsur",
        "village": "Biligere",
        "latitude": 12.3082,
        "longitude": 76.2891,
        "year": "2025-2026",
        "implementing_agency": "Karnataka Rural Infrastructure Development Ltd (KRIDL)",
        "recommended_amount": 3500000.0,
        "sanctioned_amount": 3400000.0,
        "contract_amount": 3320000.0,
        "funds_released": 2800000.0,
        "funds_paid": 2200000.0,
        "actual_expenditure": 2200000.0,
        "physical_progress": 62.0,
        "financial_progress": 64.7,
        "start_date": "2025-08-01",
        "expected_completion_date": "2026-01-15",
        "delay_days": 49,
        "overall_risk_score": 78,
        "risk_level": "CRITICAL",
        "financial_health": 70,
        "physical_health": 55,
        "contract_health": 60,
        "schedule_health": 52,
        "evidence_health": 40,
        "risk_reasons": [
            "AI Alert: Potential Duplicate Work flagged with 93% similarity to Zilla Panchayat Grant Work #ZP-MYS-2025-088 on same stretch",
            "Geotagged start coordinate aligns within 45m of previously sanctioned PWD road",
            "49-day execution delay; drain excavation incomplete at culvert crossing"
        ],
        "contractor_id": "CON-KA-078",
        "contractor_name": "Cauvery Engineering & Builders Corp",
        "last_inspected_date": "2026-02-10",
        "last_verified_date": "2026-02-15",
        "data_source": "KRIDL Karnataka & e-Manaswini System",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-KA-2025-00199",
        "title": "Formation and Concreting of Habitation Road in Biligere",
        "description": "Construction of concrete pavement and drainage in Biligere village habitation connecting temple circle.",
        "category": "Roads & Bridges",
        "status": "COMPLETED",
        "mp_name": "Prathap Simha (Previous Tenure)",
        "mp_house": "Lok Sabha",
        "state": "Karnataka",
        "district": "Mysuru",
        "constituency": "Mysore",
        "mandal_block": "Hunsur",
        "village": "Biligere",
        "latitude": 12.3086,
        "longitude": 76.2895,
        "year": "2024-2025",
        "implementing_agency": "Panchayat Raj Engineering Division Mysuru",
        "recommended_amount": 3200000.0,
        "sanctioned_amount": 3100000.0,
        "contract_amount": 3050000.0,
        "funds_released": 3050000.0,
        "funds_paid": 3050000.0,
        "actual_expenditure": 3050000.0,
        "physical_progress": 100.0,
        "financial_progress": 100.0,
        "start_date": "2024-04-10",
        "expected_completion_date": "2024-11-20",
        "delay_days": 0,
        "overall_risk_score": 15,
        "risk_level": "NORMAL",
        "financial_health": 95,
        "physical_health": 95,
        "contract_health": 92,
        "schedule_health": 95,
        "evidence_health": 92,
        "risk_reasons": ["Historical completed work referenced for duplicate spatial audit."],
        "contractor_id": "CON-KA-078",
        "contractor_name": "Cauvery Engineering & Builders Corp",
        "last_inspected_date": "2024-11-15",
        "last_verified_date": "2024-11-22",
        "data_source": "District Rural Development Authority Mysuru",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-TN-2026-00178",
        "title": "Maternal & Child Health Ward Extension at Primary Health Centre",
        "description": "Addition of 20-bed maternal care wing, neonatal observation unit, medical gas pipeline, and dedicated transformer yard at Vadipatti PHC.",
        "category": "Healthcare",
        "status": "UNDER PROGRESS",
        "mp_name": "Su. Venkatesan",
        "mp_house": "Lok Sabha",
        "state": "Tamil Nadu",
        "district": "Madurai",
        "constituency": "Madurai",
        "mandal_block": "Vadipatti",
        "village": "Alanganallur",
        "latitude": 10.0456,
        "longitude": 78.0921,
        "year": "2025-2026",
        "implementing_agency": "Tamil Nadu Medical Services Corp (TNMSC) & PWD Buildings",
        "recommended_amount": 4500000.0,
        "sanctioned_amount": 4400000.0,
        "contract_amount": 4280000.0,
        "funds_released": 3800000.0,
        "funds_paid": 3500000.0,
        "actual_expenditure": 3500000.0,
        "physical_progress": 82.0,
        "financial_progress": 81.7,
        "start_date": "2025-04-20",
        "expected_completion_date": "2025-12-31",
        "delay_days": 65,
        "overall_risk_score": 42,
        "risk_level": "WATCH",
        "financial_health": 85,
        "physical_health": 78,
        "contract_health": 82,
        "schedule_health": 60,
        "evidence_health": 88,
        "risk_reasons": [
            "65-day delay due to medical oxygen pipeline certification clearance",
            "Physical execution sound; civil works at painting and flooring stage",
            "Medical equipment procurement pending state bio-medical approval"
        ],
        "contractor_id": "CON-TN-033",
        "contractor_name": "Meenakshi Infra Consortium",
        "last_inspected_date": "2026-02-05",
        "last_verified_date": "2026-02-07",
        "data_source": "TN PWD Buildings & Directorate of Public Health",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-BR-2026-00411",
        "title": "High-Level RCC Bridge across Morhar River Tributary",
        "description": "Construction of 4-span 48m RCC bridge with approach roads to provide all-weather connectivity to 7 marooned villages during monsoon floods.",
        "category": "Roads & Bridges",
        "status": "STALLED",
        "mp_name": "Jitan Ram Manjhi",
        "mp_house": "Lok Sabha",
        "state": "Bihar",
        "district": "Gaya",
        "constituency": "Gaya",
        "mandal_block": "Barachatti",
        "village": "Sobh",
        "latitude": 24.5123,
        "longitude": 85.0182,
        "year": "2025-2026",
        "implementing_agency": "Bihar Rajya Pul Nirman Nigam Ltd (BRPNNL)",
        "recommended_amount": 5000000.0,
        "sanctioned_amount": 5000000.0,
        "contract_amount": 4900000.0,
        "funds_released": 3200000.0,
        "funds_paid": 2800000.0,
        "actual_expenditure": 2800000.0,
        "physical_progress": 38.0,
        "financial_progress": 57.1,
        "start_date": "2025-03-01",
        "expected_completion_date": "2025-10-31",
        "delay_days": 126,
        "overall_risk_score": 92,
        "risk_level": "CRITICAL",
        "financial_health": 35,
        "physical_health": 25,
        "contract_health": 40,
        "schedule_health": 20,
        "evidence_health": 55,
        "risk_reasons": [
            "126-day delay with site work halted for over 60 consecutive days",
            "Contractor abandoned pier casting post-monsoon citing aggregate rate escalation",
            "Two citizen complaints registered regarding flooded diversion track",
            "Executive Engineer issued 3rd default notice to contractor"
        ],
        "contractor_id": "CON-BR-061",
        "contractor_name": "Magadh Nirman Udyog Pvt Ltd",
        "last_inspected_date": "2026-01-28",
        "last_verified_date": "2026-02-02",
        "data_source": "BRPNNL Executive Portal & District Magistrate Office Gaya",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-RJ-2026-00052",
        "title": "Installation of 50 Solar High-Mast Lights in Gram Panchayat Chowks",
        "description": "Erection of 12m octagonal high-mast poles with 4x100W LED luminaires, lithium-ferro phosphate battery bank, and GSM IoT telemetry.",
        "category": "Solar Energy",
        "status": "UNDER PROGRESS",
        "mp_name": "Gajendra Singh Shekhawat",
        "mp_house": "Lok Sabha",
        "state": "Rajasthan",
        "district": "Jodhpur",
        "constituency": "Jodhpur",
        "mandal_block": "Luni",
        "village": "Salawas",
        "latitude": 26.1542,
        "longitude": 73.0189,
        "year": "2025-2026",
        "implementing_agency": "Rajasthan Renewable Energy Corp Ltd (RRECL)",
        "recommended_amount": 2800000.0,
        "sanctioned_amount": 2750000.0,
        "contract_amount": 2690000.0,
        "funds_released": 2400000.0,
        "funds_paid": 2100000.0,
        "actual_expenditure": 2100000.0,
        "physical_progress": 85.0,
        "financial_progress": 78.0,
        "start_date": "2025-09-01",
        "expected_completion_date": "2026-02-28",
        "delay_days": 6,
        "overall_risk_score": 24,
        "risk_level": "NORMAL",
        "financial_health": 92,
        "physical_health": 88,
        "contract_health": 90,
        "schedule_health": 85,
        "evidence_health": 94,
        "risk_reasons": [
            "42 of 50 masts installed and commissioned with functional GSM telemetry",
            "Remaining 8 masts awaiting foundation curing in sandy terrain",
            "Execution progressing within acceptable tolerance"
        ],
        "contractor_id": "CON-RJ-022",
        "contractor_name": "Marwar Water & Energy EPC Ltd",
        "last_inspected_date": "2026-02-22",
        "last_verified_date": "2026-02-25",
        "data_source": "RRECL MIS & Jodhpur Collectorate",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-WB-2026-00339",
        "title": "Modernization of Rural Sub-District Veterinary Dispensary",
        "description": "Renovation of consultation clinic, diagnostic laboratory, vaccine cold-chain facility, and animal surgery shed.",
        "category": "Healthcare",
        "status": "UNDER PROGRESS",
        "mp_name": "Raju Bista",
        "mp_house": "Lok Sabha",
        "state": "West Bengal",
        "district": "Darjeeling",
        "constituency": "Darjeeling",
        "mandal_block": "Matigara",
        "village": "Shivmandir",
        "latitude": 26.7112,
        "longitude": 88.3541,
        "year": "2025-2026",
        "implementing_agency": "Siliguri Jalpaiguri Development Authority (SJDA)",
        "recommended_amount": 2200000.0,
        "sanctioned_amount": 2150000.0,
        "contract_amount": 2080000.0,
        "funds_released": 1800000.0,
        "funds_paid": 1400000.0,
        "actual_expenditure": 1400000.0,
        "physical_progress": 68.0,
        "financial_progress": 67.3,
        "start_date": "2025-06-01",
        "expected_completion_date": "2025-12-15",
        "delay_days": 81,
        "overall_risk_score": 58,
        "risk_level": "HIGH RISK",
        "financial_health": 78,
        "physical_health": 65,
        "contract_health": 70,
        "schedule_health": 45,
        "evidence_health": 80,
        "risk_reasons": [
            "81-day delay attributable to hill region monsoons and slope stabilization",
            "Cold chain room MEP equipment arriving next week for installation",
            "Financial utilization consistent with physical milestone completion"
        ],
        "contractor_id": "CON-WB-054",
        "contractor_name": "Bengal Eastern Infra Developers",
        "last_inspected_date": "2026-02-14",
        "last_verified_date": "2026-02-16",
        "data_source": "SJDA Project Tracking & West Bengal ARD Portal",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    },
    {
        "id": "MPLAD-DL-2026-00018",
        "title": "Installation of 10 Open Air Gymnasiums & Elderly Walkways in Public Parks",
        "description": "Supply, civil foundation, and installation of weatherproof outdoor fitness stations, rubberized safety flooring, and LED solar pathways.",
        "category": "Community Infrastructure",
        "status": "COMPLETED",
        "mp_name": "Bansuri Swaraj",
        "mp_house": "Lok Sabha",
        "state": "Delhi",
        "district": "New Delhi",
        "constituency": "New Delhi",
        "mandal_block": "Chanakyapuri",
        "village": "Laxmibai Nagar Parks",
        "latitude": 28.5812,
        "longitude": 77.2089,
        "year": "2025-2026",
        "implementing_agency": "New Delhi Municipal Council (NDMC)",
        "recommended_amount": 2500000.0,
        "sanctioned_amount": 2450000.0,
        "contract_amount": 2380000.0,
        "funds_released": 2380000.0,
        "funds_paid": 2380000.0,
        "actual_expenditure": 2380000.0,
        "physical_progress": 100.0,
        "financial_progress": 100.0,
        "start_date": "2025-05-15",
        "expected_completion_date": "2025-09-30",
        "delay_days": 0,
        "overall_risk_score": 10,
        "risk_level": "NORMAL",
        "financial_health": 100,
        "physical_health": 100,
        "contract_health": 98,
        "schedule_health": 100,
        "evidence_health": 100,
        "risk_reasons": ["Flawless delivery, 100% geotagged equipment inventory registered in NDMC GIS."],
        "contractor_id": "CON-DL-009",
        "contractor_name": "National Urban Tech Infrastructure",
        "last_inspected_date": "2025-10-05",
        "last_verified_date": "2025-10-10",
        "data_source": "NDMC Smart City Project Engine",
        "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
    }
]

# Generate additional 42 realistic projects programmatically to meet >50 projects requirement
CATEGORIES = [
    "Community Infrastructure", "Roads & Bridges", "Drinking Water", 
    "Education", "Healthcare", "Sanitation", "Solar Energy", "Irrigation"
]

STATES_DISTRICTS = [
    {"state": "Andhra Pradesh", "districts": ["Visakhapatnam", "Guntur", "Krishna", "Tirupati", "Anantapur"], "mp": "M. Sribharat"},
    {"state": "Uttar Pradesh", "districts": ["Varanasi", "Gorakhpur", "Lucknow", "Prayagraj", "Agra"], "mp": "Ravi Kishan"},
    {"state": "Maharashtra", "districts": ["Pune", "Nagpur", "Nashik", "Aurangabad", "Thane"], "mp": "Nitin Gadkari"},
    {"state": "Karnataka", "districts": ["Bengaluru Rural", "Mysuru", "Dharwad", "Belagavi", "Mangaluru"], "mp": "Dr. C. N. Manjunath"},
    {"state": "Tamil Nadu", "districts": ["Madurai", "Coimbatore", "Salem", "Tiruchirappalli", "Tirunelveli"], "mp": "K. Kanimozhi"},
    {"state": "Bihar", "districts": ["Patna", "Gaya", "Muzaffarpur", "Bhagalpur", "Darbhanga"], "mp": "Ravi Shankar Prasad"},
    {"state": "Rajasthan", "districts": ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner"], "mp": "Manju Sharma"},
    {"state": "West Bengal", "districts": ["Darjeeling", "Howrah", "Asansol", "North 24 Parganas"], "mp": "Abhishek Banerjee"},
    {"state": "Gujarat", "districts": ["Vadodara", "Surat", "Rajkot", "Bhavnagar"], "mp": "C. R. Patil"},
    {"state": "Madhya Pradesh", "districts": ["Bhopal", "Indore", "Jabalpur", "Gwalior"], "mp": "Alok Sharma"}
]

TITLES_TEMPLATES = [
    "Construction of Anganwadi Centre Building with Child-Friendly Toilet",
    "Installation of Deep Borewell with Solar Submersible Pump and Water Tank",
    "Metalling and Blacktopping of Village Link Road from NH junction",
    "Construction of Stormwater Drainage and Solid Waste Segregation Shed",
    "Installation of Solar Street Lights across Habitation Wards",
    "Construction of Additional Classrooms and Library in Government Higher Secondary School",
    "Setting up of Village Primary Veterinary First Aid and Artificial Insemination Centre",
    "Upgradation of Rural Haat and Covered Vegetable Vendor Platforms",
    "Construction of Community Crematorium Shed with Solar Illumination",
    "Deepening and Desilting of Traditional Percolation Tank with Inlet Channel",
    "Supply of High-Resolution Ultrasound & Patient Monitoring Beds for Sub-Divisional Hospital",
    "Construction of Concrete Retaining Wall along Village Stream to Prevent Soil Erosion"
]

CONTRACTOR_IDS = [c["id"] for c in CONTRACTORS_DATA]
CONTRACTOR_MAP = {c["id"]: c["name"] for c in CONTRACTORS_DATA}

def generate_full_projects_list() -> List[Dict[str, Any]]:
    full_list = list(PROJECTS_RAW)
    counter = 11

    for idx, sd in enumerate(STATES_DISTRICTS):
        for d_idx, dist in enumerate(sd["districts"]):
            if len(full_list) >= 52:
                break
            
            cat = CATEGORIES[(idx + d_idx) % len(CATEGORIES)]
            title_tpl = TITLES_TEMPLATES[(idx * 3 + d_idx) % len(TITLES_TEMPLATES)]
            p_id = f"MPLAD-{sd['state'][:2].upper()}-2026-{counter:05d}"
            
            sanction = float((15 + ((idx * 7 + d_idx * 5) % 35)) * 100000) # ₹15 Lakh to ₹50 Lakh
            contract_amt = float(round(sanction * 0.97, -3))
            
            # Stagger statuses and risks
            status_mod = counter % 4
            if status_mod == 0:
                status = "COMPLETED"
                phys = 100.0
                fin = 100.0
                delay = 0
                risk = 12 + (counter % 15)
                risk_lvl = "NORMAL"
                exp = contract_amt
                rel = contract_amt
            elif status_mod == 1:
                status = "UNDER PROGRESS"
                phys = float(65 + (counter % 25))
                fin = float(68 + (counter % 20))
                delay = (counter % 35)
                risk = 25 + (counter % 20)
                risk_lvl = "NORMAL" if risk < 30 else "WATCH"
                exp = round(contract_amt * (fin / 100.0), -3)
                rel = round(contract_amt * 0.85, -3)
            elif status_mod == 2:
                status = "UNDER PROGRESS"
                phys = float(45 + (counter % 20))
                fin = float(72 + (counter % 15)) # Fin exceeds Phys
                delay = 45 + (counter % 60)
                risk = 55 + (counter % 25)
                risk_lvl = "HIGH RISK"
                exp = round(contract_amt * (fin / 100.0), -3)
                rel = round(contract_amt * 0.80, -3)
            else:
                status = "UNDER PROGRESS" if counter % 2 == 0 else "STALLED"
                phys = float(30 + (counter % 20))
                fin = float(60 + (counter % 25))
                delay = 75 + (counter % 50)
                risk = 76 + (counter % 20)
                risk_lvl = "CRITICAL"
                exp = round(contract_amt * (fin / 100.0), -3)
                rel = round(contract_amt * 0.75, -3)

            con_id = CONTRACTOR_IDS[counter % len(CONTRACTOR_IDS)]
            
            full_list.append({
                "id": p_id,
                "title": f"{title_tpl} in {dist} Rural",
                "description": f"MPLADS developmental work sanction for {title_tpl.lower()} under district plan.",
                "category": cat,
                "status": status,
                "mp_name": sd["mp"],
                "mp_house": "Lok Sabha",
                "state": sd["state"],
                "district": dist,
                "constituency": f"{dist} Parliamentary",
                "mandal_block": f"Block {chr(65 + (counter % 8))}",
                "village": f"Gram {dist} Kalan",
                "latitude": 15.0 + (idx * 1.5) + (d_idx * 0.3),
                "longitude": 75.0 + (idx * 1.2) + (d_idx * 0.4),
                "year": "2025-2026",
                "implementing_agency": "District Rural Development Authority (DRDA)",
                "recommended_amount": sanction + 50000.0,
                "sanctioned_amount": sanction,
                "contract_amount": contract_amt,
                "funds_released": rel,
                "funds_paid": exp,
                "actual_expenditure": exp,
                "physical_progress": phys,
                "financial_progress": fin,
                "start_date": "2025-06-01",
                "expected_completion_date": "2026-01-31",
                "delay_days": delay,
                "overall_risk_score": min(95, risk),
                "risk_level": risk_lvl,
                "financial_health": max(20, 100 - int(abs(fin - phys) * 1.8)),
                "physical_health": max(20, int(phys)),
                "contract_health": max(30, 95 - int(delay * 0.5)),
                "schedule_health": max(15, 100 - delay),
                "evidence_health": 85,
                "risk_reasons": [
                    f"Schedule delay of {delay} days observed" if delay > 0 else "Milestones on schedule",
                    f"Financial progress Δ {round(abs(fin - phys), 1)}% relative to physical completion" if abs(fin - phys) > 10 else "Expenditure aligned with physical progress"
                ],
                "contractor_id": con_id,
                "contractor_name": CONTRACTOR_MAP.get(con_id),
                "last_inspected_date": "2026-02-15",
                "last_verified_date": "2026-02-18",
                "data_source": "MPLADS e-SAKSHI State Data Integration",
                "source_verification_status": "VERIFIED_GOVERNMENT_RECORD"
            })
            counter += 1
            
    return full_list

ALL_PROJECTS = generate_full_projects_list()
